# Generated by Django 4.2.20 on 2025-04-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='es_superusuario',
            field=models.BooleanField(default=False),
        ),
    ]
