# Generated by Django 4.2.20 on 2025-04-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_turnos', '0002_usuarios_es_superusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='es_superusuario',
        ),
    ]
