# Generated by Django 4.2.20 on 2025-04-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_turnos', '0003_remove_usuarios_es_superusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='referencia',
        ),
        migrations.AddField(
            model_name='turnos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
